"""Interactive first-time setup: Alpaca keys, .env, ingest, first cycle."""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from alpaca.common.exceptions import APIError

from src.config import PROJECT_ROOT, Settings, get_settings, hub_sqlite_path, parquet_dir
from src.data.adapters.yfinance_adapter import YFinanceAdapter
from src.data.pipeline import DataPipeline
from src.data.storage.parquet_store import ParquetStore
from src.data.storage.sqlite_store import SQLiteStore
from src.execution.alpaca_adapter import AlpacaBrokerAdapter
from src.execution.errors import ConfigurationError

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger(__name__)


def validate_alpaca_keys(key: str, secret: str) -> tuple[bool, str]:
    """Return ``(True, equity_str)`` on success or ``(False, error_message)``."""
    try:
        broker = AlpacaBrokerAdapter.create(key.strip(), secret.strip(), paper=True)
        eq = broker.get_account_equity()
        return True, str(float(eq))
    except (APIError, ConfigurationError) as exc:
        logger.critical("Alpaca API rejected credentials or request: %s", exc)
        return False, str(exc)
    except (ConnectionError, TimeoutError, OSError) as exc:
        logger.warning("Network error validating Alpaca keys: %s", exc)
        return False, str(exc)
    except ValueError as exc:
        logger.warning("Unexpected account data from Alpaca: %s", exc)
        return False, str(exc)


def write_env_file(path: Path, keys: dict[str, str], *, overwrite: bool = False) -> bool:
    """Write ``.env`` from key/value pairs. Returns ``False`` if file exists and ``overwrite`` is false."""
    if path.exists() and not overwrite:
        return False
    lines: list[str] = [
        "# Carmel — generated by carmel setup",
        "",
    ]
    ak = (keys.get("alpaca_api_key") or "").strip()
    sk = (keys.get("alpaca_secret_key") or "").strip()
    if ak and sk:
        lines.extend(
            [
                f"ALPACA_API_KEY={ak}",
                f"ALPACA_SECRET_KEY={sk}",
                "ALPACA_PAPER=true",
            ],
        )
    fred = (keys.get("fred_api_key") or "").strip()
    lines.append(f"FRED_API_KEY={fred}")
    wh = (keys.get("webhook_url") or "").strip()
    if wh:
        lines.extend(
            [
                "NOTIFICATION__ENABLED=true",
                f"NOTIFICATION__WEBHOOK_URL={wh}",
            ],
        )
    lines.append("LOG_LEVEL=INFO")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return True


def run_initial_ingest(settings: Settings) -> dict[str, bool]:
    """Ingest OHLCV for every symbol the configuration requires. Returns symbol -> success."""
    from src.data.symbol_resolver import resolve_required_symbols

    syms = resolve_required_symbols(settings)
    parquet = ParquetStore(parquet_dir(settings))
    sqlite = SQLiteStore(hub_sqlite_path(settings))
    adapter = YFinanceAdapter()
    dcfg = settings.data
    pipeline = DataPipeline(
        adapter=adapter,
        parquet_store=parquet,
        sqlite_store=sqlite,
        ohlcv_outlier_zscore_threshold=dcfg.ohlcv_outlier_zscore_threshold,
        ohlcv_min_prior_for_zscore=dcfg.ohlcv_min_prior_for_zscore,
        ohlcv_max_abs_daily_return=dcfg.ohlcv_max_abs_daily_return,
        validation_exempt_symbols=dcfg.validation_exempt_symbols,
        initial_backfill_years=dcfg.initial_backfill_years,
    )
    out: dict[str, bool] = {}
    for sym in sorted(syms):
        r = pipeline.ingest_ohlcv(sym)
        out[sym] = r.success
        logger.info("Ingest %s: %s", sym, "OK" if r.success else "FAILED")
    return out


def run_setup_wizard() -> None:
    """Interactive CLI: keys, optional FRED/webhook, .env, ingest, first cycle."""
    print("=== Carmel Setup ===\n")
    print(
        "This wizard configures your paper trading environment.\n"
        "You'll need an Alpaca paper trading account: https://app.alpaca.markets/\n",
    )

    keys_ok = False
    last_credential_error: str | None = None
    while not keys_ok:
        ak = input("Alpaca API Key: ").strip()
        sk = input("Alpaca Secret Key: ").strip()
        if not ak or not sk:
            print("Keys cannot be empty.")
            continue
        ok, msg = validate_alpaca_keys(ak, sk)
        if ok:
            keys_ok = True
            print(f"Connected to Alpaca paper account (equity: ${float(msg):,.2f})")
        else:
            last_credential_error = msg
            print(f"Connection failed: {msg}")
            retry = input("Retry? (Y/n): ").strip().lower()
            if retry == "n":
                try:
                    from src.automation.runner import notify_operational_critical

                    notify_operational_critical(
                        get_settings(),
                        category="alpaca_credentials",
                        message=(
                            "Alpaca API rejected credentials during setup validation: "
                            f"{last_credential_error or msg}"
                        ),
                    )
                except (OSError, RuntimeError, ValueError, TypeError) as notify_exc:
                    logger.warning("Could not send credential alert to notifier: %s", notify_exc)
                print("Skipping Alpaca validation — trading cycles will not work without keys.")
                ak, sk = "", ""
                break

    fred = input("FRED API Key (optional, press Enter to skip): ").strip()
    webhook = input("Webhook URL for alerts (optional, press Enter to skip): ").strip()

    env_path = PROJECT_ROOT / ".env"
    payload: dict[str, str] = {
        "alpaca_api_key": ak,
        "alpaca_secret_key": sk,
        "fred_api_key": fred,
        "webhook_url": webhook,
    }
    if env_path.exists():
        ow = input(".env already exists. Overwrite? (y/N): ").strip().lower()
        overwrite = ow == "y"
    else:
        overwrite = True

    if (ak and sk) or fred or webhook:
        if write_env_file(env_path, payload, overwrite=overwrite):
            print("Wrote .env")
        elif not overwrite:
            print("Leaving existing .env unchanged.")
    else:
        print("No credentials to write — skipping .env.")

    get_settings.cache_clear()
    settings = get_settings()

    print("\nIngesting market data for configured universe...")
    results = run_initial_ingest(settings)
    for sym, ok in sorted(results.items()):
        status = "OK" if ok else "FAILED"
        print(f"  {sym} — {status}")

    print("\nRunning first paper trading cycle...")
    if keys_ok and ak and sk:
        from src.automation.runner import create_trading_workflow

        wf = create_trading_workflow(settings)
        wf.run_cycle(as_of=None)
        print("First cycle complete.")
    else:
        print("Skipping first cycle (no Alpaca keys).")

    print(
        "\n=== Setup Complete ===\n\n"
        "Dashboard:  streamlit run src/dashboard/app.py\n"
        "Daemon:     carmel run\n"
        "One cycle:  carmel once\n"
        "Config:     carmel config\n\n"
        "Paper trading is ON (safe mode). Edit config/settings.yaml to customize strategies.\n",
    )
